In [1]:

my_list = [10, 20, 30, 40, 50]
print(f"Original List: {my_list}")

my_list.append(60)
print(f"After append(60): {my_list}")

my_list.extend([70, 80])
print(f"After extend([70, 80]): {my_list}")

my_list.insert(0, 5)  
print(f"After insert(0, 5): {my_list}")

my_list.remove(40)
print(f"After remove(40): {my_list}")

popped_item = my_list.pop(1)  # Remove item at index 1 (which is 10)
print(f"After pop(1): {my_list} (Popped item: {popped_item})")


index_of_30 = my_list.index(30)
print(f"Index of 30: {index_of_30}")

my_list.append(30) 
count_of_30 = my_list.count(30)
print(f"Count of 30: {count_of_30}")

my_list.sort()
print(f"After sort(): {my_list}")

my_list.reverse()
print(f"After reverse(): {my_list}")

my_list.clear()
print(f"After clear(): {my_list}")


Original List: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(0, 5): [5, 10, 20, 30, 40, 50, 60, 70, 80]
After remove(40): [5, 10, 20, 30, 50, 60, 70, 80]
After pop(1): [5, 20, 30, 50, 60, 70, 80] (Popped item: 10)
Index of 30: 2
Count of 30: 2
After sort(): [5, 20, 30, 30, 50, 60, 70, 80]
After reverse(): [80, 70, 60, 50, 30, 30, 20, 5]
After clear(): []


In [3]:

student_names = ('madhu', 'nandan', 'Charlie')

try:
    student_names[1] = 'maddy'
except TypeError as e:
    print(f"Error: {e}")

print(f"Original tuple: {student_names}")


Error: 'tuple' object does not support item assignment
Original tuple: ('madhu', 'nandan', 'Charlie')


A tuple is an ordered,immutable collection of items.
The key characteristic of a tuple is that,once created,its contents cannot be changed

In [4]:
original_list = [1, 2, 2, 3, 4, 4, 4, 5, 6, 6]
my_set = set(original_list)
print(my_set)

{1, 2, 3, 4, 5, 6}


The output contains only unique numbers because the set() function automatically handles the removal of duplicate elements from the original list. 
Sets are specifically designed to store only one instance of any given value, making them useful for operations where uniqueness is required

In [5]:
person = {
    'name': 'Nandan',
    'age': 25,
    'city': 'Bengaluru'
}

person['age'] = 26

person['email'] = 'nandan@example.com'

print(person)


{'name': 'Nandan', 'age': 26, 'city': 'Bengaluru', 'email': 'nandan@example.com'}


Dictionary creation uses curly braces, while updating or adding keys is done via the {Link: assignment operator (=) https://nandan.org/datascience/python/dictionary-dict-function}

In [6]:
age = int(input("Please enter your age: "))
if age >= 18:
    print(f"You are {age} years old. You are eligible to vote!")
else:
    print(f"You are {age} years old. You are not eligible to vote yet.")

Please enter your age:  25


You are 25 years old. You are eligible to vote!


In [9]:
marks = int(input("Enter the marks: "))
if marks >= 90:
    print('A')
elif marks >= 75:
    print('B')
elif marks >= 50:
    print('C')
else:
    print('Fail')

Enter the marks:  33


Fail


In [10]:
num = int(input("Enter a number: "))

if num > 0:
    if num % 2 == 0:
        print(f"{num} is Positive and Even.")
    else:
        print(f"{num} is Positive and Odd.")
elif num == 0:
    print("The number is Zero.")
else:
    print(f"{num} is Negative.")

Enter a number:  45


45 is Positive and Odd.


In [12]:
import numpy as np

scalar = np.array(5)
print(f"Scalar:\n{scalar}\n")

array_1d = np.arange(1, 6)
print(f"1D Array:\n{array_1d}\n")

array_2d = np.arange(10, 70, 10).reshape(2, 3)
print(f"2D Array:\n{array_2d}\n")


Scalar:
5

1D Array:
[1 2 3 4 5]

2D Array:
[[10 20 30]
 [40 50 60]]



In [13]:
import numpy as np
random_array = np.random.randint(low=0, high=101, size=(4, 4))
print(random_array)


[[61 37 95  7]
 [27  0 12 93]
 [70  1 87 59]
 [64  8 73 27]]


In [14]:
import numpy as np
import pandas as pd
numpy_array = np.zeros((3, 3))
df = pd.DataFrame(numpy_array, columns=['A', 'B', 'C'])
print(df)

     A    B    C
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0


In [21]:
import pandas as pd
import numpy as np

data = {
    'Name': ['nandan', 'maddy', 'Charlie', 'Dravid', 'Eshvar', 'Frank', 'Gracy', 'Harsha', 'shivu', 'Jay'],
    'Age': [25, 32, 18, 47, 35, 29, 41, 22, 30, 38],
    'City': ['bengaluru', 'shimoga', 'raichur', 'Hubli', 'Mysuru', 'Navalgunda', 'mandya', 'Chitradurga', 'Hubli', 'Mumbai'],
    'Salary': [60000,  np.nan, 45000, 80000, 75000, 62000, np.nan, 48000, 71000, 85000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
      Name  Age         City   Salary
0   nandan   25    bengaluru  60000.0
1    maddy   32      shimoga      NaN
2  Charlie   18      raichur  45000.0
3   Dravid   47        Hubli  80000.0
4   Eshvar   35       Mysuru  75000.0
5    Frank   29   Navalgunda  62000.0
6    Gracy   41       mandya      NaN
7   Harsha   22  Chitradurga  48000.0
8    shivu   30        Hubli  71000.0
9      Jay   38       Mumbai  85000.0


In [22]:
print("\nDataFrame Info:")
df.info()

print("\nDataFrame Description:")
print(df.describe())


DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

DataFrame Description:
             Age        Salary
count  10.000000      8.000000
mean   31.700000  65750.000000
std     8.870049  14538.127213
min    18.000000  45000.000000
25%    26.000000  57000.000000
50%    31.000000  66500.000000
75%    37.250000  76250.000000
max    47.000000  85000.000000


In [23]:
name_city_df = df[['Name', 'City']]
print("\nSelected 'Name' and 'City' columns:")
print(name_city_df)


Selected 'Name' and 'City' columns:
      Name         City
0   nandan    bengaluru
1    maddy      shimoga
2  Charlie      raichur
3   Dravid        Hubli
4   Eshvar       Mysuru
5    Frank   Navalgunda
6    Gracy       mandya
7   Harsha  Chitradurga
8    shivu        Hubli
9      Jay       Mumbai


In [24]:
df_dropped = df.drop(columns=['City'])
print("\nDataFrame after dropping 'City' column:")
print(df_dropped)


DataFrame after dropping 'City' column:
      Name  Age   Salary
0   nandan   25  60000.0
1    maddy   32      NaN
2  Charlie   18  45000.0
3   Dravid   47  80000.0
4   Eshvar   35  75000.0
5    Frank   29  62000.0
6    Gracy   41      NaN
7   Harsha   22  48000.0
8    shivu   30  71000.0
9      Jay   38  85000.0


In [25]:
salary_mean = df['Salary'].mean()
df['Salary'].fillna(salary_mean, inplace=True)
print(f"\nMean salary used for filling NaNs: {salary_mean}")
print("DataFrame after filling missing 'Salary' values:")
print(df)


Mean salary used for filling NaNs: 65750.0
DataFrame after filling missing 'Salary' values:
      Name  Age         City   Salary
0   nandan   25    bengaluru  60000.0
1    maddy   32      shimoga  65750.0
2  Charlie   18      raichur  45000.0
3   Dravid   47        Hubli  80000.0
4   Eshvar   35       Mysuru  75000.0
5    Frank   29   Navalgunda  62000.0
6    Gracy   41       mandya  65750.0
7   Harsha   22  Chitradurga  48000.0
8    shivu   30        Hubli  71000.0
9      Jay   38       Mumbai  85000.0


C:\Users\NANDAN\AppData\Local\Temp\ipykernel_1752\91750557.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(salary_mean, inplace=True)


In [26]:
df_no_duplicates = df.drop_duplicates()
print("\nDataFrame after removing duplicates:")
print(df_no_duplicates)


DataFrame after removing duplicates:
      Name  Age         City   Salary
0   nandan   25    bengaluru  60000.0
1    maddy   32      shimoga  65750.0
2  Charlie   18      raichur  45000.0
3   Dravid   47        Hubli  80000.0
4   Eshvar   35       Mysuru  75000.0
5    Frank   29   Navalgunda  62000.0
6    Gracy   41       mandya  65750.0
7   Harsha   22  Chitradurga  48000.0
8    shivu   30        Hubli  71000.0
9      Jay   38       Mumbai  85000.0
